name: Code QA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull

    - name: Show problems
      continue-on-error: true
      run: |
        flake8 app.py core/*.py
    - name: Run QA Tests
      run: |
        isort app.py core/*.py
        autopep8 --in-place app.py core/*.py
        ttws app.py core/*.py
    - name: Show unresolved problems
      run: |
        flake8 app.py core/*.py

    - name: Commit changes
      continue-on-error: true
      run: |
        git add app.py core/*.py
        git commit -m "[auto]: Fix code style"
        git push
